#!/bin/sh

SYSROOT=/home/nicolas/carino/out/staging
export PKG_CONFIG_PATH=${SYSROOT}/lib/pkgconfig

export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig
#export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}

exec pkg-config "$@"
