#!/bin/bash

if [ "$V" = "1" ]; then
	set -x
fi

set -e

. config/build_config

on_exit() {
	kill -9 ${inot_pid}
}

# the place monitored for file creation
local_prefix=${FINAL_DIR}
mkdir -p ${local_prefix}

# the output of the watch, listing all the created files
list_file=/tmp/bau.list
rm -f ${list_file}
inotifywait --monitor --recursive --event create,moved_to,modify ${local_prefix} \
		    --outfile ${list_file} &

inot_pid=$!

trap "on_exit" 2 3 15

# TODO should replace this by a notification on inotify readiness
#sleep 1

# call the build script
./build.sh "$@"

set +e
adb shell mount -orw,remount / > /dev/null 2>&1

sort --unique ${list_file} | while read line
do
	filename=${line##* }
	if [ "${filename}" = ".gitignore" ]; then
		continue
	fi
	local_path=${line%% *}
	full_path=${local_path}/${filename}
	# TODO for symbolic links, don't continue, rather create them on target
	if [ ! -f "${full_path}" ] || [ -L "${full_path}" ]; then
		continue
	fi
	remote_path=/${local_path#${local_prefix}}
	local_md5=$(md5sum "${local_path}/${filename}" | cut -f 1 -d ' ')
	remote_md5=$(adb shell md5sum "${remote_path}/${filename}" | cut -f 1 -d ' ')
	if [ "${local_md5}" = "${remote_md5}" ]; then
		continue
	fi
	echo adb push ${local_path}/${filename} ${remote_path}/
	adb push ${local_path}/${filename} ${remote_path}/
done

echo adb shell sync

on_exit
